export const AUTHENTICATED = "AUTHENTICATED";
export const LOGOUT = "LOGOUT";
export const GET_UPCOMING_CONFERENCE ="GET_UPCOMING_CONFERENCE";
export const UPDATE_USER = "UPDATE_USER";
export const GET_AGENDA_EVENTS = "GET_AGENDA_EVENTS";
export const CLEAR_AGENDA_EVENTS = "CLEAR_AGENDA_EVENTS";
export const GET_PRESENTATION_PLAN = "GET_PRESENTATION_PLAN";
export const GET_ALL_PARTICIPANTS = "GET_PARTICIPANTS";